# Generated by Django 5.2.2 on 2025-06-04 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
                ('precio_base', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_recomendada', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion', models.CharField(max_length=50)),
                ('incluye', models.TextField(help_text='Separar por comas los servicios incluidos')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_personas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('CONF', 'Confirmada'), ('CANC', 'Cancelada'), ('COMP', 'Completada')], default='PEND', max_length=4)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viajes.paquete')),
            ],
        ),
    ]
